# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

fail_fast = false

[[repos]]
repo = "local"
hooks = [
  {
    id = "nix-dev-configure",
    name = "nix run .#configure",
    entry = "nix run .#configure",
    language = "system",
    pass_filenames = false,
    stages = ["pre-commit"]
  }
]

[[repos]]
repo = "https://github.com/pocc/pre-commit-hooks"
rev = "v1.3.5"
hooks = [
  {
    id = "clang-format",
    args = ["--style=file"],
    files = "\\.(c|cc|cpp|cxx|h|hpp)$"
  },
  { 
    id = "clang-tidy",
    args = ["-p=.nix-dev/build"],
    files = "\\.(c|cc|cpp|cxx|h|hpp)$"
  },
  {
    id = "cppcheck",
    pass_filenames = false,
    args = [
      "--project=.nix-dev/build/compile_commands.json",
      "--enable=all",
      "--inline-suppr",
      "--error-exitcode=1"
    ],
  }
]
