(* Top-level structural statements *)
spec
    = "spec", IDENTIFIER, "{", { spec_member }, "}";

spec_member
    = field
    | invariant;

field
    = "field", IDENTIFIER, ":", type, "{", { check }, "}";

check
    = "check", ":", expression, ";";

invariant
    = "invariant", IDENTIFIER, "{", expression, ";", "}";