(* Define possible types for checks *)
type
    = union_type;

union_type
    = intersection_type, { "|", intersection_type };

primary_type
    = simple_type
    | array_type
    | map_type
    | "(", type, ")";

simple_type
    = "number"
    | "integer"
    | "string"
    | "boolean"
    | IDENTIFIER;

array_type
    = "array", "<", type, ">";

map_type
    = "map", "<", type, ",", type, ">";